[build]
publish = "publish"
command = "cp -R src publish"

[[plugins]]
package = "@netlify/plugin-sitemap"

  [plugins.inputs]
  prettyURLs = true
  trailingSlash = true

[[redirects]]
from = "/contact-2/*"
to = "/contact/:splat"
